services:
  - type: web
    name: spar-erp-2026
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn spar_etl_receiver:app
    envVars:
      - key: CLOUDFLARE_API_URL
        sync: false
